# Generated by Django 5.0.3 on 2024-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('tables', 'tablets'), ('capsules', 'capsules'), ('injectables', 'injectables'), ('solutions', 'solutions'), ('sachets', 'sachets')], max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_number', models.CharField(max_length=50, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('quantity_of_packs', models.IntegerField(default=0, null=True)),
                ('cost_per_pack', models.IntegerField(default=0.0, null=True)),
                ('units_per_pack', models.IntegerField(default=0, null=True)),
                ('markup', models.IntegerField(default=0, null=True)),
                ('cost_per_unit_bp', models.IntegerField(default=0.0, null=True)),
                ('cost_per_unit_sp', models.IntegerField(default=0.0, null=True)),
                ('total_amount', models.IntegerField(default=0.0, null=True)),
                ('quantity_recieved', models.IntegerField(default=0, null=True)),
                ('received_by', models.CharField(max_length=50, null=True)),
                ('quantity_issued', models.IntegerField(default=0, null=True)),
                ('issued_from', models.CharField(max_length=50, null=True)),
                ('issued_by', models.CharField(max_length=50, null=True)),
                ('issued_to', models.CharField(max_length=50, null=True)),
                ('phone_number_r', models.CharField(max_length=50, null=True)),
                ('entered_by', models.CharField(max_length=50, null=True)),
                ('phone_number_e', models.CharField(max_length=50, null=True)),
                ('reorder_level', models.IntegerField(default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
