# Generated by Django 5.0.3 on 2024-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0002_items_issued_by_internally_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quantity_recieved',
            new_name='quantity_received',
        ),
        migrations.AddField(
            model_name='items',
            name='received_by_internally',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
