# Generated by Django 5.0.3 on 2024-03-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0003_rename_quantity_recieved_items_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, choices=[('tablets', 'tablets'), ('capsules', 'capsules'), ('injectables', 'injectables'), ('solutions', 'solutions'), ('sachets', 'sachets')], max_length=50, null=True),
        ),
    ]
